let arr = [
  "Hurzuf",
  "Novinki",
  "Gorkhā",
  "State of Haryāna",
  "Holubynka",
  "Bāgmatī Zone",
  "Mar’ina Roshcha",
  "Republic of India",
  "Kathmandu",
  "Laspi",
  "Merida",
  "Vinogradovo",
  "Qarah Gawl al ‘Ulyā",
  "Cherkizovo",
  "Alupka",
  "Lichtenrade",
  "Zavety Il’icha",
  "‘Azriqam",
  "Ghūra",
  "Tyuzler",
  "Zaponor’ye",
  "Il’ichëvka",
  "Partyzans’ke",
  "Yurevichi",
  "Gumist’a",
  "Ptitsefabrika",
  "Orekhovo",
  "Birim",
  "Priiskovyy",
  "Dzhaga",
  "Tret’ya Rota",
  "Ruislip",
  "Karow",
  "Gatow",
  "Mkuze",
  "Lhasa",
  "İstanbul",
  "Mao",
  "Russian Federation",
  "De-Friz",
  "Rumbak",
  "Vavibet",
  "Surtagān Chib",
  "Rīgas Rajons",
  "Verkhneye Shchekotikhino",
  "Bucha",
  "Republic of Poland",
  "Kuchary",
  "North America",
  "Brumaire",
  "Ishikawa-ken",
  "Matoba",
  "Pya",
  "Kalanac",
  "Federal Republic of Germany",
  "Land Nordrhein-Westfalen",
  "Mutaykutan",
  "Nalchik",
  "Kolganov",
  "Rybatskiy",
  "Bellara",
  "Bartlett",
  "Rietfontein",
  "Hardap",
  "Botswana",
  "El Destierro",
  "Jones Crossroads",
  "Vernon Parish",
  "Pennick",
  "Black Bear Spring",
  "Bee House",
  "Morden",
  "Nasirotu",
  "Sisali",
  "Puntan",
  "Tsiémé-Mandiélé",
  "Masama",
  "Purukcahu",
  "Néméyong II",
  "Pondok Genteng",
  "Mbongoté",
  "Amiling",
  "Kélkoto",
  "Angetu",
  "Massa",
  "Tumko",
  "Moskva",
  "Japan",
  "Hokkaidō",
  "Sanggrahan",
  "Karangmangle",
  "Sheremetyevskiy",
  "Yershovo",
  "Znamenka",
  "Lisbon",
  "Walbrzych",
  "Naklo nad Notecia",
  "Zhengzhou",
  "Tonyrefail",
  "Bankra",
  "Europe",
  "Moskovskaya Oblast’",
  "Provo",
  "Tejon",
  "Guliston",
  "Ciciler",
  "Bilmece",
  "Provincia de Pontevedra",
  "Carmarthenshire",
  "Helsinki",
  "Gemeente Wervershoof",
  "Forville",
  "Tall ‘Alāwī",
  "La Portanière",
  "East Portlemouth",
  "Whyalla",
  "Terrace End",
  "Hashimoto",
  "Tsukuba-kenkyūgakuen-toshi",
  "Higashi-asahimachi",
  "Hanabatachō",
  "Senzaki",
  "Sakaki",
  "Daisen",
  "Ikaruga",
  "Matsuzaki",
  "Noboribetsu",
  "Grandate",
  "Biella",
  "Soverato",
  "Pinerolo",
  "Dundee City",
  "Nuneaton and Bedworth District",
  "Rhyl",
  "Foulridge",
  "Hermitage",
  "Golcar",
  "Thornbury",
  "Peterhof",
  "Grebnevo",
  "Centro Habana",
  "Carolina",
  "Gustavia",
  "Xianju",
  "Tōkyō-to",
  "Washington",
  "San Dimas",
  "Culfa",
  "Bandar Emām Khomeynī",
  "Shāhrūd",
  "Bo",
  "Daché",
  "Département de l'Ouest",
  "Montescudo",
  "San Pedro",
  "Wels(Stadt)",
  "Palmerston",
  "Telmankend",
  "Neftcala",
  "Pushkino",
  "Visé",
  "Lede",
  "Ieper",
  "Titao",
  "Cascades",
  "Villazon",
  "Laval",
  "Yangambi",
  "Watsa",
  "Wamba",
  "Lusambo",
  "Luebo",
  "Lubao",
  "Kampene",
  "Kabinda",
  "Kabare",
  "Businga",
  "Nioki",
  "Mushie",
  "Mangai",
  "Ville de Kinshasa",
  "Luzern",
  "Fahrweid (südl. Teil)",
  "Riehen",
  "Bärenbohl",
  "Letten",
  "Touba",
  "Tonga",
  "Lahovičky",
  "Svépravice",
  "Wardenburg",
  "Wachtberg",
  "Schwalmtal",
  "Pfaffenhofen an der Ilm",
  "Odenthal",
  "Much",
  "Großstädteln",
  "Lindlar",
  "Kreuzau",
  "Höxter, Stadt",
  "Kreis Unna",
  "Hille",
  "Haar",
  "Grossenhain",
  "Ginsheim-Gustavsburg",
  "Engelskirchen",
  "Eggenstein-Leopoldshafen",
  "Brüggen",
  "Bönen",
  "Kreisfreie Stadt Bielefeld",
  "Bielefeld",
  "Baiersbronn",
  "Bad Zwischenahn",
  "Bad Honnef, Stadt",
  "Ascheberg",
  "Ostfildern",
  "Spremberg, Stadt",
  "Høje-Taastrup Kommune",
  "Nyborg Kommune",
  "Kolding Kommune",
  "Neiba",
  "Moca",
  "el hed",
  "Souma",
  "Rouached",
  "Reggane",
  "Metlili Chaamba",
  "El Abiodh Sidi Cheikh",
  "Osuna",
  "Lora del Río",
  "Fuengirola",
  "Bailén",
  "Utebo",
  "Barberà del Vallès",
  "Pinto",
  "Pineda de Mar",
  "Palamós",
  "Navalcarnero",
  "Mejorada del Campo",
  "Manlleu",
  "Leganés",
  "Laguna de Duero",
  "Coruña (A)",
  "Illescas",
  "la Roca del Vallès",
  "Ermua",
  "Eibar",
  "Durango",
  "Collado Villalba",
  "Ciempozuelos",
  "Caldes de Montbui",
  "Calahorra",
  "Benicasim/Benicàssim",
  "Realejos (Los)",
  "Basauri",
  "Lobras",
  "Robit",
  "Mekele",
  "Kolito",
  "Lambasa",
  "Sokehs Municipality",
  "Wittenheim",
  "Wattrelos",
  "Vitré",
  "Viry-Châtillon",
  "Villeneuve-le-Roi",
  "Vierzon",
  "Verrières-le-Buisson",
  "Arrondissement d'Antony",
  "Vallauris",
  "Tourcoing",
  "Taverny",
  "Soisy-sous-Montmorency",
  "Sin-le-Noble",
  "Sèvres",
  "Salon-de-Provence",
  "Saint-Ouen",
  "Saint-Fons",
  "Saint-Avold",
  "Rezé",
  "Pontivy",
  "Pessac",
  "Palaiseau",
  "Ozoir-la-Ferrière",
  "Oullins",
  "Mougins",
  "Morsang-sur-Orge",
  "Montélimar",
  "Montbéliard",
  "Maisons-Alfort",
  "Louviers",
  "Limeil-Brévannes",
  "Les Pavillons-sous-Bois",
  "Lattes",
  "Grigny",
  "Goussainville",
  "Gien",
  "Gagny",
  "Firminy",
  "Échirolles",
  "Décines-Charpieu",
  "Dammarie-les-Lys",
  "Colombes",
  "Cognac",
  "Chenôve",
  "Chelles",
  "Cesson-Sévigné",
  "Cayenne",
  "Carvin",
  "Bonneuil-sur-Marne",
  "Belfort",
  "Bayeux",
  "Bagnolet",
  "Autun",
  "Auch",
  "Annecy-le-Vieux",
  "Alfortville",
  "Les Ulis",
  "Yate",
  "Caia Park",
  "Worcester District",
  "Borough of Wolverhampton",
  "Winsford",
  "Welwyn Hatfield",
  "Borough of Trafford",
  "Tamworth District",
  "Wroughton",
  "Dartford District",
  "South Derbyshire District",
  "Borough of Tameside",
  "Mossley",
  "Seaham",
  "Sandown",
  "Ryton",
  "Redditch District",
  "Prestatyn",
  "Peterlee",
  "Penarth",
  "Oswestry",
  "Northwich",
  "Ards District",
  "Newtownards",
  "Newquay",
  "Nailsea",
  "Morley",
  "Mirfield",
  "Maesteg",
  "Sutton",
  "City of Westminster",
  "Sefton",
  "East Dunbartonshire",
  "East Ayrshire",
  "Keynsham",
  "Kempston",
  "Horwich",
  "Dacorum District",
  "Hastings District",
  "Guisborough",
  "Great Yarmouth District",
  "South Staffordshire District",
  "Goole",
  "Fareham District",
  "Epsom and Ewell District",
  "Runnymede District",
  "Ebbw Vale",
  "Broxtowe District",
  "Dunstable",
  "City of Derby",
  "Eccleshill",
  "Cwmbran Central",
  "Healeyfield",
  "Ribble Valley District",
  "Sodbury",
  "Brymbo",
  "Brixham",
  "Bracknell",
  "Blyth",
  "Biggleswade",
  "Berkhamsted",
  "Bathampton",
  "North Down District",
  "Bangor",
  "Banbridge District",
  "Aberystwyth",
  "Chalk Farm",
  "East Dorset District",
  "Poti",
  "Tafo",
  "Shama Junction",
  "Saltpond",
  "Dunkwa",
  "Pita",
  "Sainte-Anne",
  "Pointe-à-Pitre",
  "Les Abymes",
  "Le Moule",
  "Capesterre-Belle-Eau",
  "Dimos Salamis",
  "Dimos Fyli",
  "Grytviken",
  "Municipio de San Marcos",
  "Municipio de Flores",
  "Departamento de Valle",
  "Thor",
  "Ti Port-de-Paix",
  "Csukásitanyák",
  "Tanjungbalai",
  "Reuleuet",
  "Judieda Makr",
  "Yeola",
  "Yellapur",
  "Yaval",
  "Ventimiglia",
  "Savona",
  "Ruvo di Puglia",
  "Pioltello",
  "Palestrina",
  "Palagiano",
  "Pagani",
  "Orta Nova",
  "Oria",
  "Noicattaro",
  "Nettuno",
  "Negrar",
  "Mira",
  "Lissone",
  "Lastra a Signa",
  "Imperia",
  "Jesi",
  "Giugliano in Campania",
  "Galatone",
  "Gaeta",
  "Frosinone",
  "Formigine",
  "Fondi",
  "Fidenza",
  "Corciano",
  "Conversano",
  "Cittadella",
  "Bra",
  "Benevento",
  "Bareggio",
  "Arese",
  "Aprilia",
  "Anagni",
  "Spinea",
  "Volla",
  "Old Harbour",
  "New Kingston",
  "Kimiidera",
  "Mocimboa",
  "Gemeente Noordwijkerhout",
  "Gemeente Leusden",
  "Gemeente Huizen",
  "Gemeente Hoogeveen",
  "Gemeente Heemskerk",
  "Gemeente Alphen aan den Rijn",
  "Horten",
  "Haugesund",
  "Gjøvik",
  "Ålesund",
  "Tulsipur",
  "Cambridge",
  "Bidbid",
  "Bawshar",
  "Badiyah",
  "As Suwayq",
  "Uchiza",
  "Włocławek",
  "Świdwin",
  "Jastrzębie-Zdrój",
  "Bełchatów",
  "Aguadilla",
  "Vila Franca de Xira",
  "Ramada",
  "Almada",
  "Gueifães",
  "Safonovo",
  "Lillsjönäs",
  "Koidu",
  "Prakhon Chai",
  "Changwat Lop Buri",
  "Kocaali",
  "Vwawa",
  "Coffee County",
  "Clay County",
  "Flagler County",
  "Hernando County",
  "Sumter County",
  "Fulton County",
  "DeKalb County",
  "Clark County",
  "Sylvania",
  "Clark County",
  "City of Baltimore",
  "Cashell Estates",
  "Wakely Terrace",
  "Saint Charles County",
  "City of Saint Louis",
  "Coahoma County",
  "Jackson County",
  "Nash County",
  "Lee County",
  "Warren County",
  "Creek County",
  "Richland County",
  "Taylor County",
  "Hidalgo County",
  "Washington County",
  "Walker County",
  "Kerr County",
  "City of Alexandria",
  "City of Bristol",
  "City of Charlottesville",
  "City of Chesapeake",
  "City of Colonial Heights",
  "City of Danville",
  "City of Fairfax",
  "City of Fredericksburg",
  "City of Harrisonburg",
  "City of Hopewell",
  "City of Lynchburg",
  "City of Manassas",
  "City of Newport News",
  "City of Norfolk",
  "City of Petersburg",
  "City of Portsmouth",
  "City of Radford",
  "City of Richmond",
  "City of Roanoke",
  "City of Salem",
  "City of Suffolk",
  "City of Staunton",
  "City of Waynesboro",
  "City of Winchester",
  "Cuyahoga County",
  "Lee County",
  "Knox County",
  "Ottawa County",
  "Bay County",
  "Macomb County",
  "Ingham County",
  "Shiawassee County",
  "Nassau County",
  "Kings County",
  "Cortland County",
  "City Line",
  "Fulton County",
  "Jamestown",
  "Queensbridge Houses",
  "Carnegie Hill",
  "Rensselaer County",
  "Mahoning County",
  "Delaware County",
  "Allen County",
  "Erie County",
  "Bristol County",
  "Santa Cruz County",
  "San Francisco County",
  "Grand Junction",
  "Maverick County",
  "Gray County",
  "Shofirkon",
  "Qushkupir",
  "Parkent",
  "Pop",
  "Paxtakor",
  "Novyy Turtkul",
  "Manghit",
  "Haqqulobod",
  "Iskandar",
  "Hazorasp",
  "Chinoz",
  "Buka",
  "Beruniy",
  "Bektemir",
  "Quva",
  "Redemption",
  "Municipio Anaco",
  "Anaco",
  "Municipio Zamora",
  "Municipio Valencia",
  "Municipio Santiago Mariño",
  "Municipio San Felipe",
  "Municipio Colón",
  "Municipio San Carlos",
  "Municipio Los Salias",
  "Municipio Sucre",
  "Municipio Libertador",
  "Palo Negro",
  "Municipio Nirgua",
  "Mucumpiz",
  "Municipio Juan José Mora",
  "Los Rastrojos",
  "Municipio José Félix Ribas",
  "Municipio Santos Michelena",
  "Las Tejerias",
  "Lagunillas",
  "Municipio Vargas",
  "Municipio Marcano",
  "Municipio Valdez",
  "Municipio Zamora",
  "Municipio Plaza",
  "Municipio Mario Briceño Iragorry",
  "El Limon",
  "Municipio El Hatillo",
  "Municipio Chacao",
  "Tacarigua",
  "Municipio Baruta",
  "Municipio José Tadeo Monagas",
  "Municipio García de Hevia",
  "Tỉnh Nghệ An",
  "Tỉnh Phú Thọ",
  "Viet Tri",
  "Tỉnh Quảng Ninh",
  "Tỉnh Phú Yên",
  "Thornhill",
  "Port Hope",
  "Estado de Jalisco",
  "Tabasco",
  "Holdereggen",
  "Landkreis Saarlouis",
  "Sachsen",
  "Straße",
  "Burghaun",
  "Kiedrich",
  "Haiterbach",
  "Neuenberg",
  "Schlaitdorf",
  "Thale",
  "Treuchtlingen",
  "Klein Glienicke",
  "Ostbevern",
  "Eselsburg",
  "Reifert",
  "Gemeente Leeuwarden",
  "Het Hazebos",
  "Musiskwartier",
  "Suhr",
  "Albardon",
  "Buzovna",
  "Amirdzhan",
  "Aghsu Rayon",
  "Satkhira",
  "Roeselare",
  "Puurs",
  "Province du Zoundwéogo",
  "Garango",
  "Province du Soum",
  "Province de la Tapoa",
  "Muramvya",
  "Tchaourou",
  "Bassila",
  "Viana",
  "Sao Joao dos Inhamuns",
  "Solanea",
  "Sobradinho",
  "Bondo",
  "Ippy",
  "Puerto Quellon",
  "Nacimiento",
  "Mbanga",
  "Mamfe",
  "Ksar Chellala",
  "Kerkera",
  "El Affroun",
  "Al Qurayn",
  "Al Ayyat",
  "Abu al Matamir",
  "Zoba Gash-Barka",
  "Metahara",
  "Korem",
  "Giyon",
  "Gimbi",
  "Genet",
  "Finote Selam",
  "Dodola",
  "Butajira",
  "Asaita",
  "Asasa",
  "Areka",
  "Saint-Jean-de-la-Ruelle",
  "Saint-Herblain",
  "Saint-Étienne",
  "Saint-Cyr-sur-Loire",
  "Paris",
  "Arrondissement de Boulogne-sur-Mer",
  "Outreau",
  "Orvault",
  "Arrondissement de Metz-Ville",
  "Maurepas",
  "Laon",
  "La Crau",
  "La Courneuve",
  "Gentilly",
  "Garches",
  "Croix",
  "Couëron",
  "Tanjungtiram",
  "Percut",
  "Perbaungan",
  "Labuhan Deli",
  "Deli Tua",
  "Bireun",
  "Wiradesa",
  "Weru",
  "Welahan",
  "Wangon",
  "Ungaran",
  "Tulungagung",
  "Tayu",
  "Randudongkal",
  "Plumbon",
  "Parung",
  "Panji",
  "Pangkalanbuun",
  "Pamulang",
  "Pakisaji",
  "Lahat",
  "Labuan",
  "Kutoarjo",
  "Kroya",
  "Krian",
  "Klungkung",
  "Kijang",
  "Ketanggungan",
  "Jekulo",
  "Godean",
  "Cimahi",
  "Buduran",
  "Bondowoso",
  "Bojonegoro",
  "Bima",
  "Bangil",
  "Maghar",
  "Wokha",
  "Warora",
  "Waraseoni",
  "Wadi",
  "Virarajendrapet",
  "Virar",
  "Vettaikkaranpudur",
  "Vedaraniyam",
  "Vayalar",
  "Vasudevanallur",
  "Vadakku Valliyur",
  "Usilampatti",
  "Uravakonda",
  "Uran",
  "Upleta",
  "Uppal Kalan",
  "Unnao",
  "Unjha",
  "Un",
  "Umreth",
  "Umred",
  "Turaiyur",
  "Todaraisingh",
  "Titlagarh",
  "Tisaiyanvilai",
  "Tiruvalla",
  "Terdal",
  "Teonthar",
  "Tekkali",
  "Tekari",
  "Tarn Taran",
  "Tarana",
  "Tanuku",
  "Tanakpur",
  "Talwara"
];
export default arr;
